#!/usr/bin/env bash
# prydc — Pride package manager and build tool
# "The over-engineered C" — compiler toolchain
#
# Usage:
#   prydc new <name>          Create a new Pride package
#   prydc build               Build the current package
#   prydc run                 Build and run the current package
#   prydc check               Type-check without emitting IR
#   prydc add <dep[@ver]>     Add a dependency (git URL or local path)
#   prydc fetch               Fetch/update all declared dependencies
#   prydc clean               Remove build artifacts
#   prydc info                Show package info
#   prydc init                Init a Pride.toml in current directory

set -e

PRIDE_VERSION="0.1.0"
PRYDC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRIDE_BIN="${PRYDC_DIR}/../pride"
BUILD_DIR=".pride/build"
DEPS_DIR=".pride/deps"
MANIFEST="Pride.toml"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'

info()  { echo -e "${BLUE}[prydc]${RESET} $*"; }
ok()    { echo -e "${GREEN}[prydc]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[prydc]${RESET} $*"; }
die()   { echo -e "${RED}[prydc] error:${RESET} $*" >&2; exit 1; }

# ── TOML parser (minimal, line-oriented) ─────────────────────────────────────
toml_get() {
    local file="$1" key="$2"
    grep -E "^${key}\s*=" "$file" 2>/dev/null \
        | head -1 | sed 's/^[^=]*=\s*//' | tr -d '"' | tr -d "'" | xargs
}

toml_get_array() {
    local file="$1" key="$2"
    # Extract array values between [ and ]
    awk "/^${key}\s*=/{found=1} found && /\[/{in_arr=1} in_arr{gsub(/[\[\]\"]/,\"\"); print} in_arr && /\]/{exit}" "$file" \
        | grep -oE '"[^"]*"|[a-zA-Z0-9_./:-]+' | tr -d '"' | xargs
}

# Read deps section: [[dependencies]] blocks
read_deps() {
    local file="$1"
    python3 - "$file" << 'PYEOF'
import sys, re
content = open(sys.argv[1]).read()
# Find all [[dependencies]] blocks
blocks = re.split(r'\[\[dependencies\]\]', content)[1:]
for block in blocks:
    lines = block.strip().split('\n')
    dep = {}
    for line in lines:
        if '=' in line and not line.startswith('['):
            k, v = line.split('=', 1)
            dep[k.strip()] = v.strip().strip('"\'')
    if 'name' in dep:
        path = dep.get('path', '')
        git  = dep.get('git', '')
        ver  = dep.get('version', 'latest')
        print(f"{dep['name']}|{path}|{git}|{ver}")
PYEOF
}

# ── Commands ──────────────────────────────────────────────────────────────────

cmd_new() {
    local name="$1"
    [ -z "$name" ] && die "Usage: prydc new <name>"
    [ -d "$name" ] && die "Directory '$name' already exists"
    mkdir -p "$name/src"
    cat > "$name/Pride.toml" << EOF
[package]
name    = "${name}"
version = "0.1.0"
authors = []
edition = "2026"

[build]
entry   = "src/main.pie"
stdlib  = true

# [[dependencies]]
# name    = "mylib"
# path    = "../mylib"
# version = "0.1.0"
EOF
    cat > "$name/src/main.pie" << 'EOF'
-- src/main.pie — entry point
fn main : () -> i64
  | () -> 0
EOF
    ok "Created package '${name}'"
    info "Run:  cd ${name} && prydc build"
}

cmd_init() {
    [ -f "$MANIFEST" ] && die "Pride.toml already exists"
    local name
    name=$(basename "$(pwd)")
    cat > "$MANIFEST" << EOF
[package]
name    = "${name}"
version = "0.1.0"
authors = []
edition = "2026"

[build]
entry   = "src/main.pie"
stdlib  = true
EOF
    ok "Initialized Pride.toml for '${name}'"
}

cmd_check_manifest() {
    [ -f "$MANIFEST" ] || die "No Pride.toml found. Run 'prydc init' or 'prydc new <name>'"
}

cmd_fetch() {
    cmd_check_manifest
    mkdir -p "$DEPS_DIR"
    local fetched=0
    while IFS='|' read -r dep_name dep_path dep_git dep_ver; do
        [ -z "$dep_name" ] && continue
        local dest="$DEPS_DIR/$dep_name"
        if [ -n "$dep_path" ]; then
            if [ -d "$dep_path" ]; then
                info "Linking local dep '$dep_name' from $dep_path"
                ln -sfn "$(realpath "$dep_path")" "$dest"
                fetched=$((fetched+1))
            else
                warn "Local path '$dep_path' for dep '$dep_name' not found"
            fi
        elif [ -n "$dep_git" ]; then
            if [ -d "$dest/.git" ]; then
                info "Updating '$dep_name' from $dep_git"
                git -C "$dest" pull --quiet
            else
                info "Fetching '$dep_name' from $dep_git"
                git clone --quiet "$dep_git" "$dest"
            fi
            fetched=$((fetched+1))
        fi
    done < <(read_deps "$MANIFEST")
    ok "Fetched $fetched dependencies"
    # Write lockfile: record resolved commit hashes for reproducible builds
    {
        printf "# Pride.lock — generated by prydc fetch\n"
        printf "# DO NOT EDIT. Commit this file for reproducible builds.\n"
        printf "version = 1\n\n"
        while IFS='|' read -r dep_name dep_path dep_git dep_ver; do
            [ -z "$dep_name" ] && continue
            local dest="$DEPS_DIR/$dep_name"
            printf "[[dependency]]\n"
            printf "name = \"%s\"\n" "$dep_name"
            printf "version = \"%s\"\n" "$dep_ver"
            if [ -n "$dep_git" ]; then
                printf "git = \"%s\"\n" "$dep_git"
                if [ -d "$dest/.git" ]; then
                    local hash
                    hash=$(git -C "$dest" rev-parse HEAD 2>/dev/null || echo "unknown")
                    printf "commit = \"%s\"\n" "$hash"
                fi
            elif [ -n "$dep_path" ]; then
                printf "path = \"%s\"\n" "$dep_path"
            fi
            printf "\n"
        done < <(read_deps "$MANIFEST")
    } > "Pride.lock"
    info "Lockfile written: Pride.lock"
}

collect_sources() {
    local manifest="$1"
    local entry
    entry=$(toml_get "$manifest" "entry")
    [ -z "$entry" ] && entry="src/main.pie"

    local sources=("$entry")

    # Include stdlib if requested
    local use_stdlib
    use_stdlib=$(toml_get "$manifest" "stdlib")
    if [ "$use_stdlib" = "true" ]; then
        local stdlib_dir="${PRYDC_DIR}/../stdlib"
        if [ -d "$stdlib_dir" ]; then
            while IFS= read -r f; do
                sources+=("$f")
            done < <(find "$stdlib_dir" -name "*.pie" | sort)
        fi
    fi

    # Include extra sources listed in [build] sources array
    local extra_sources
    extra_sources=$(toml_get_array "$manifest" "sources")
    for s in $extra_sources; do
        sources+=("$s")
    done

    # Include deps
    if [ -d "$DEPS_DIR" ]; then
        while IFS= read -r f; do
            sources+=("$f")
        done < <(find "$DEPS_DIR" -name "*.pie" | sort)
    fi

    printf '%s\n' "${sources[@]}"
}

cmd_test() {
    cmd_check_manifest
    local pkg_name
    pkg_name=$(toml_get "$MANIFEST" "name")
    local entry
    entry=$(toml_get "$MANIFEST" "entry")
    [ -z "$entry" ] && entry="src/main.pie"

    mkdir -p "$BUILD_DIR"

    # Collect sources
    local sources=()
    while IFS= read -r s; do sources+=("$s"); done < <(collect_sources "$MANIFEST")

    info "Discovering tests in ${#sources[@]} source files"

    # Run pride --test to discover test functions
    local test_list
    test_list=$("$PRIDE_BIN" --test "${sources[@]}" 2>/dev/null | grep "^\[test\]" | awk '{print $2}')

    if [ -z "$test_list" ]; then
        warn "No test functions found (prefix fn names with test_ or annotate with #[test])"
        return 0
    fi

    local test_count
    test_count=$(echo "$test_list" | wc -l)
    info "Found $test_count test function(s)"

    # Generate a test harness main file
    local harness="${BUILD_DIR}/__test_harness.pie"
    {
        printf "-- Auto-generated test harness\n"
        printf "fn __test_main : () -> i64\n"
        printf "  | () ->\n"
        printf "      let mut passed : i64 = 0\n"
        printf "      let mut failed : i64 = 0\n"
        while IFS= read -r tfn; do
            [ -z "$tfn" ] && continue
            printf "      %s()\n" "$tfn"
            printf "      passed = passed + 1\n"
        done <<< "$test_list"
        printf "      failed\n"
    } > "$harness"

    # Build with harness
    local ll_out="${BUILD_DIR}/${pkg_name}_test.ll"
    local bin_out="${BUILD_DIR}/${pkg_name}_test"

    if ! "$PRIDE_BIN" --emit-llvm "$ll_out" "${sources[@]}" "$harness" 2>&1; then
        die "Test binary compilation failed"
    fi

    local bc_out="${BUILD_DIR}/${pkg_name}_test.bc"
    local obj_out="${BUILD_DIR}/${pkg_name}_test.o"
    local rt_obj="${BUILD_DIR}/runtime.o"

    llvm-as-22 "$ll_out" -o "$bc_out" 2>&1 || die "llvm-as-22 failed"
    llc-22 -O0 -filetype=obj "$bc_out" -o "$obj_out" 2>&1 || die "llc-22 failed"
    [ -f "${BUILD_DIR}/runtime.o" ] || cc -O2 -c "$(dirname "$PRIDE_BIN")/../runtime/runtime.c" -o "$rt_obj" 2>&1

    ld.lld-22 \
        /usr/lib/x86_64-linux-gnu/crt1.o /usr/lib/x86_64-linux-gnu/crti.o \
        /usr/lib/gcc/x86_64-linux-gnu/14/crtbeginS.o \
        "$obj_out" "$rt_obj" \
        /usr/lib/gcc/x86_64-linux-gnu/14/crtendS.o /usr/lib/x86_64-linux-gnu/crtn.o \
        -o "$bin_out" \
        -L/usr/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu \
        -L/usr/lib/gcc/x86_64-linux-gnu/14 \
        -lc -lm -lpthread -lgcc -lgcc_s \
        --dynamic-linker /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 2>&1 \
    || die "Linking test binary failed"

    ok "Test binary: $bin_out"
    info "Running $test_count test(s)..."
    "$bin_out"
    local exit_code=$?
    if [ "$exit_code" = "0" ]; then
        ok "All $test_count test(s) passed"
    else
        die "$exit_code test(s) failed"
    fi
}

cmd_build() {
    cmd_check_manifest
    local pkg_name
    pkg_name=$(toml_get "$MANIFEST" "name")
    local entry
    entry=$(toml_get "$MANIFEST" "entry")
    [ -z "$entry" ] && entry="src/main.pie"

    [ -f "$entry" ] || die "Entry point '$entry' not found"

    mkdir -p "$BUILD_DIR"

    # Collect all source files
    local sources=()
    while IFS= read -r s; do
        sources+=("$s")
    done < <(collect_sources "$MANIFEST")

    local ll_out="${BUILD_DIR}/${pkg_name}.ll"
    local bc_out="${BUILD_DIR}/${pkg_name}.bc"
    local obj_out="${BUILD_DIR}/${pkg_name}.o"
    local bin_out="${BUILD_DIR}/${pkg_name}"

    info "Building ${pkg_name} (${#sources[@]} source files)"

    # Step 1: Pride → LLVM IR
    if ! "$PRIDE_BIN" --emit-llvm "$ll_out" "${sources[@]}" 2>&1; then
        die "Pride compiler failed"
    fi

    # Step 2: llvm-as
    if ! llvm-as-22 "$ll_out" -o "$bc_out" 2>&1; then
        die "llvm-as-22 failed"
    fi

    # Step 3: llc (optimized)
    local opt_level
    opt_level=$(toml_get "$MANIFEST" "opt_level")
    [ -z "$opt_level" ] && opt_level="2"
    if ! llc-22 -O"$opt_level" -filetype=obj "$bc_out" -o "$obj_out" 2>&1; then
        die "llc-22 failed"
    fi

    # Step 4: link with runtime
    local runtime_obj=""
    local runtime_c="${PRYDC_DIR}/../runtime/runtime.c"
    if [ -f "$runtime_c" ]; then
        runtime_obj="${BUILD_DIR}/runtime.o"
        cc -O2 -c "$runtime_c" -o "$runtime_obj" 2>&1
    fi

    local link_args=("$obj_out")
    [ -n "$runtime_obj" ] && link_args+=("$runtime_obj")

    # CRT objects for a working main() entry point
    local crt1="/usr/lib/x86_64-linux-gnu/crt1.o"
    local crti="/usr/lib/x86_64-linux-gnu/crti.o"
    local crtn="/usr/lib/x86_64-linux-gnu/crtn.o"
    local crtbegin="/usr/lib/gcc/x86_64-linux-gnu/14/crtbeginS.o"
    local crtend="/usr/lib/gcc/x86_64-linux-gnu/14/crtendS.o"
    local crt_start=(); local crt_end=()
    [ -f "$crt1" ]     && crt_start+=("$crt1")
    [ -f "$crti" ]     && crt_start+=("$crti")
    [ -f "$crtbegin" ] && crt_start+=("$crtbegin")
    [ -f "$crtend" ]   && crt_end+=("$crtend")
    [ -f "$crtn" ]     && crt_end+=("$crtn")

    if ! ld.lld-22 "${crt_start[@]}" "${link_args[@]}" "${crt_end[@]}" -o "$bin_out" \
        -L/usr/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu \
        -L/usr/lib/gcc/x86_64-linux-gnu/14 \
        -lc -lm -lpthread -lgcc -lgcc_s \
        --dynamic-linker /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 2>&1; then
        die "ld.lld-22 failed"
    fi

    ok "Built ${pkg_name} → ${bin_out}"
}

cmd_run() {
    cmd_build
    local pkg_name
    pkg_name=$(toml_get "$MANIFEST" "name")
    local bin_out="${BUILD_DIR}/${pkg_name}"
    info "Running ${pkg_name}"
    exec "$bin_out" "$@"
}

cmd_check() {
    cmd_check_manifest
    local sources=()
    while IFS= read -r s; do sources+=("$s"); done < <(collect_sources "$MANIFEST")
    info "Checking ${#sources[@]} source files"
    "$PRIDE_BIN" "${sources[@]}"
    ok "Check complete"
}

cmd_clean() {
    cmd_check_manifest
    rm -rf "$BUILD_DIR"
    ok "Cleaned build directory"
}

cmd_add() {
    local dep="$1"
    [ -z "$dep" ] && die "Usage: prydc add <name@version> or <git-url>"
    cmd_check_manifest

    # Detect git URL vs name
    if echo "$dep" | grep -qE "^https?://|^git@|\.git$"; then
        local git_url="$dep"
        local dep_name
        dep_name=$(basename "$git_url" .git)
        cat >> "$MANIFEST" << EOF

[[dependencies]]
name    = "${dep_name}"
git     = "${git_url}"
version = "latest"
EOF
        ok "Added dependency '${dep_name}' from ${git_url}"
        info "Run 'prydc fetch' to download"
    else
        local dep_name="${dep%%@*}"
        local dep_ver="${dep##*@}"
        [ "$dep_ver" = "$dep" ] && dep_ver="latest"
        cat >> "$MANIFEST" << EOF

[[dependencies]]
name    = "${dep_name}"
version = "${dep_ver}"
EOF
        ok "Added dependency '${dep_name}@${dep_ver}'"
        warn "No registry URL set — add 'git' or 'path' field manually in Pride.toml"
    fi
}

cmd_info() {
    cmd_check_manifest
    local name version authors entry
    name=$(toml_get "$MANIFEST" "name")
    version=$(toml_get "$MANIFEST" "version")
    authors=$(toml_get "$MANIFEST" "authors")
    entry=$(toml_get "$MANIFEST" "entry")
    echo -e "${BOLD}Package:${RESET} ${name}"
    echo -e "${BOLD}Version:${RESET} ${version}"
    echo -e "${BOLD}Authors:${RESET} ${authors}"
    echo -e "${BOLD}Entry:${RESET}   ${entry:-src/main.pry}"
    echo -e "${BOLD}Pride:${RESET}   $("$PRIDE_BIN" --version 2>/dev/null || echo 'pride')"
    local ndeps
    ndeps=$(read_deps "$MANIFEST" | wc -l)
    echo -e "${BOLD}Deps:${RESET}    ${ndeps}"
}

cmd_help() {
    echo -e "${BOLD}prydc${RESET} v${PRIDE_VERSION} — The over-engineered C package manager"
    echo ""
    echo "USAGE:"
    echo "  prydc <command> [args]"
    echo ""
    echo "COMMANDS:"
    echo "  new <name>     Create a new package"
    echo "  init           Initialize Pride.toml in current directory"
    echo "  build          Build the package"
    echo "  run [args]     Build and run"
    echo "  check          Type-check without building
  test           Build and run all test functions"
    echo "  add <dep>      Add a dependency"
    echo "  fetch          Download/update all dependencies"
    echo "  clean          Remove build artifacts"
    echo "  info           Show package information"
    echo "  help           Show this help"
}

# ── Dispatch ──────────────────────────────────────────────────────────────────
CMD="${1:-help}"
shift || true

case "$CMD" in
    new)       cmd_new "$@" ;;
    init)      cmd_init ;;
    build)     cmd_build ;;
    run)       cmd_run "$@" ;;
    check)     cmd_check ;;
    test)      cmd_test ;;
    add)       cmd_add "$@" ;;
    fetch)     cmd_fetch ;;
    clean)     cmd_clean ;;
    info)      cmd_info ;;
    lock)      cmd_fetch ;;  # alias: prydc lock regenerates Pride.lock
    help|--help|-h) cmd_help ;;
    version|--version|-v) echo "prydc $PRIDE_VERSION" ;;
    *)         die "Unknown command '$CMD'. Run 'prydc help'." ;;
esac
